config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('material/', include('material.urls', namespace='material')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

material/urls.py
from django.urls import path
from material.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, MaterialDeleteView
from material.apps import MaterialConfig

app_name = MaterialConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

store/urls.py
from django.urls import path
from store.views import StudentListView, StudentDetailView, ContactsCreateView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggle_activity
from store.apps import StoreConfig

app_name = StoreConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', StudentUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name="toggle_activity")
]

material/models.py
from django.db import models


class Material(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True)
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "материал"
        verbose_name_plural = "материалы"

store/models.py
from django.db import models

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Student(models.Model):
    first_name = models.CharField(max_length=200, verbose_name='имя')
    second_name = models.CharField(max_length=200, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)  # РАСПАКОВЫВАЕМ СЛОВАРЬ

    is_active = models.BooleanField(default=True, verbose_name='учится')

    def __str__(self):
        return f'{self.first_name} {self.second_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('second_name',)


class Contacts(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.URLField(max_length=100, verbose_name='адрес')
    massage = models.CharField(max_length=100, verbose_name='краткое описание')

    def __str__(self):
        return f'{self.name} {self.email}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('name',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name="название")
    description = models.TextField(verbose_name='описание')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='студент')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'

store/forms.py
from django import forms
from store.models import Student, Subject

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

material/views.py
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from material.models import Material


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body',)
    success_url = reverse_lazy('material:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class MaterialListView(ListView):
    model = Material

    """ добавляем фильтр показывать активные публикации"""

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class MaterialDetailView(DetailView):
    model = Material

    """ добавляем счетчик просмотры"""
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body',)
    #success_url = reverse_lazy('material:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('material:view', args=[self.kwargs.get('pk')])


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('material:list')

store/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse

from store.forms import StudentForm, SubjectForm
from store.models import Student, Contacts, Subject
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class StudentListView(ListView):
    model = Student



class StudentDetailView(DetailView):
    model = Student


class ContactsCreateView(CreateView):
    model = Contacts
    fields = ('name', 'email', 'massage',)
    success_url = reverse_lazy('store:list')

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('store:list')



class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('store:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST)
        else:
            context_data['formset'] = SubjectFormset()
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('store:list')


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)

    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True
    student_item.save()
    return redirect(reverse('store:list'))

material/templates/material/material_confirm_delete.html
{% extends 'store/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col=4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить запись "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-outline-danger form-control m-2">
                            Подтвердить
                        </button>
                        <a href="{% url 'material:list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

material/templates/material/material_detail.html
{% extends 'store/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Материалы "{{ object.title }}" {{ object.slug}}
                    </h3>
                </div>
                <div class="card-bode">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

material/templates/material/material_form.html
{% extends 'store/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col=4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary form-control m-2">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

material/templates/material/material_list.html
{% extends 'store/base.html' %}
{% block content%}

<div class="col-12-mb-4">
  <a class="btn btn-outline-success" href="{% url 'material:create' %}">Добавить материалы</a>
</div>

{% for object in object_list %}
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">
      <div class="card-body">
        <p class="card-text">
          {{ object|title }}
        </p>
        <div class="d-flex-justify-content-between align-items-center">
          <div class="btn-group">
            <a href="{% url 'material:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">view</a>
            <a href="{% url 'material:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">edit</a>
            <a href="{% url 'material:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}

store/templates/store/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">О нас</h4>
              <p class="text-muted">тут какая то информация о нас.</p>
            </div>
            {% include 'store/includes/inc_main_menu.html' %}

          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'store:list' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Университет божественных наук</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
      </section>


      <div class="album py-5">
        <div class="container">
          <div class="row">
              {% block content%}
              {% endblock %}
        </div>
      </div>
    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">

        </p>
        <p>&copy; {% now 'Y' %}</p>
        <p>
          <a href="{% url 'store:list' %}" type="button" class="btn btn-sm btn-outline-secondary">вернуться на главную страницу</a>
        </p>

      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

store/templates/store/contacts_form.html
{% extends 'store/base.html '%}

{% block content %}

<div class="col-12">
    <div class="card form-control">
        <div class="card-body form-control">
            <h3 class="card-title">Оставьте заявку</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
              <button type="submit" class="btn btn-outline-primary form-control m-2">ОТПРАВИТЬ ЗАЯВКУ</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

store/templates/store/includes/inc_main_menu.html
<div class="col-sm-4 offset-md-1 py-4">
    <h4 class="text-white">Меню</h4>
    <ul class="list-unstyled">
        <li><a href="{% url 'store:list' %}" class="text-white">Главное</a></li>
        <li><a href="{% url 'material:list' %}" class="text-white">Материалы</a></li>
        <li><a href="{% url 'store:contacts' %}" class="text-white">Контакты</a></li>
    </ul>
</div>

store/templates/store/student_confirm_delete.html
{% extends 'store/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col=4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить запись "{{ object }}"?</p>
                        <button type="submit" class="btn btn-outline-danger form-control m-2">
                            Подтвердить
                        </button>
                        <a href="{% url 'store:list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/student_detail.html
{% extends 'store/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.first_name }}
                        {{ object.second_name }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {% if object.is_active %}
                        Статус: Учится
                        {% else %}
                        Статус: Не учится
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <img src="/media/{{ object.avatar }}" Width="300" Height="250"/>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/student_form.html
{% extends 'store/base.html '%}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3>
                            добавить ученика
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary form-control m-2">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3>
                            предмет ученика
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

store/templates/store/student_list.html
{% extends 'store/base.html' %}
{% block content%}

<div class="col-12-mb-5">
  <a class="btn btn-outline-success" href="{% url 'store:create' %}">
    ДОБАВИТЬ УЧЕНИКА</a>
</div>
{% for object in object_list %}

<div class="col-6-mb-5">
  <div class="card mb-5 box-shadow">
    <img src="/media/{{ object.avatar }}" alt="Avatar" Width="300" Height="250">
    <div class="container">
      <h4><b>УЧЕНИК</b></h4>
      <p>
        {% if object.is_active %}
        {{ object }}
        {% else %}
        {{ object }}
        {% endif %}
      </p>
    </div>
    <div class="btn-group">
      <a href="{% url 'store:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">view</a>
      <a href="{% url 'store:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">edit</a>
      <a href="{% url 'store:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">delete</a>
    </div>
    {% if object.is_active %}
    <a class="btn btn-warning" href="{% url 'store:toggle_activity' object.pk %}">Деактивировать</a>
    {% else %}
    <a class="btn btn-success" href="{% url 'store:toggle_activity' object.pk %}">Aктивировать</a>
    {% endif %}
  </div>
</div>

{% endfor %}
{% endblock %}